### ISSUE TITLE
Bouton submit ?

### ISSUE THREAD

**Issue by VConsulting** [wysow/wysow-postfinance#10]
Bonjour,

Est il possible de remplacer le bouton classic par une image ?
Merci

**Comment by wysow** [comment]
Bonjour, sans plus de contexte difficile de répondre, et comme il s'agit d'un système de paiement bancaire il est possible que cette option ne soit pas disponible.

**Comment by wysow** [comment]
Je ferme cette issue pour inactivité, n'hésitez pas à la rouvrir si besoin.
