### ISSUE TITLE
Support of Twint is not avaliable

### ISSUE THREAD

**Issue by Axent96** [wysow/wysow-postfinance#11]
Do you can please add the Twint Methode here & create new version for the change?-

https://github.com/wysow/wysow-postfinance/blob/05aef57e07d342cfa4db6f28218ab031ed57d411/lib/PostFinance/AbstractPaymentRequest.php#L82

'TWINT' => 'TWINT'

thank you very munch

**Comment by wysow** [comment]
Hello @vlobovikov is that the only needed change to make twint.ch work with this lib? If so feel free to make a PR as I'm not actively using this project right now. Thanks a lot.

**Comment by Axent96** [comment]
No, postfinance support right now the twint as payment method.

**Comment by wysow** [comment]
If it already support it then feel free to make a PR to add it. I will accept it and tag a new version.

**Comment by Axent96** [comment]
I made a PR. Do you can please approve & merge it?

**Comment by wysow** [comment]
Merged and released.
