### ISSUE TITLE
List of possible parameters to include in the SHA-OUT calculation

### ISSUE THREAD

**Issue by SiddhyN** [wysow/wysow-postfinance#6]
Hi,

First thx for your code. I use it and it work very weel.

Then I had a problem checking the SHAOUT signature at the server-to-server return. I noticed that there were some parameters missing in the filter to calculate the hash chain.

By adding all the parameters provided by Postfinance, the correspondence is good.

Maybe this list has been changed since the time?

Here is the list I used: 
https://e-payment-postfinance.v-psp.com/~/media/kdb/integration%20guides/sha-out_params.ashx?la=fr

Hopefully it will be useful to others.

Have a good day

**Comment by wysow** [comment]
Hello @SiddhyN and thanks for your feedback on this.

Can you elaborate a bit more on what you really changed so that your application works as expected?

Thanks in advance.

**Comment by SiddhyN** [comment]
Hi,

Ok i try to elaborate a bit more :)

I modified the [$allowed] parameter of the [PostFinance\ParameterFilter\ShaOutParameterFilter] class to add all possible return variables specified in the postfinance documentation. (For me it was the PAYIDSUB variable that was missing)

Here is my new definition:
`    private $allowed = array(
        'AAVADDRESS', 'AAVCHECK', 'AAVMAIL', 'AAVNAME', 'AAVPHONE', 'AAVZIP', 'ACCEPTANCE', 'ALIAS', 'AMOUNT',
        'BIC', 'BIN', 'BRAND', 'CARDNO', 'CCCTY', 'CN', 'COLLECTOR_BIC', 'COLLECTOR_IBAN', 'COMPLUS', 'CREATION_STATUS',
        'CREDITDEBIT', 'CURRENCY', 'CVCCHECK', 'DCC_COMMPERCENTAGE', 'DCC_CONVAMOUNT', 'DCC_CONVCCY', 'DCC_EXCHRATE',
        'DCC_EXCHRATESOURCE', 'DCC_EXCHRATETS', 'DCC_INDICATOR', 'DCC_MARGINPERCENTAGE', 'DCC_VALIDHOURS', 'DEVICEID',
        'DIGESTCARDNO', 'ECI', 'ED', 'EMAIL', 'ENCCARDNO', 'FXAMOUNT', 'FXCURRENCY', 'IP', 'IPCTY', 'MANDATEID', 'MOBILEMODE',
        'NBREMAILUSAGE', 'NBRIPUSAGE', 'NBRIPUSAGE_ALLTX', 'NBRUSAGE', 'NCERROR', 'ORDERID', 'PAYID', 'PAYIDSUB',
        'PAYMENT_REFERENCE', 'PM', 'SCO_CATEGORY', 'SCORING', 'SEQUENCETYPE', 'SIGNDATE', 'STATUS', 'SUBBRAND',
        'SUBSCRIPTION_ID', 'TRXDATE', 'VC'
    );`

Hoping to have been a little clearer

**Comment by wysow** [comment]
Oh sure I get it now!

If you want you can do a pull request for this to be incorporated in my lib, I welcome new contributors anytime... ;)

And thanks for noticing this.

**Comment by SiddhyN** [comment]
I see that you did the PR. Thank you :)
And thank you again for your library

I will watch next time to do the PR myself :)

Have a good day
