### ISSUE TITLE
Parametre manquant

### ISSUE THREAD

**Issue by VConsulting** [wysow/wysow-postfinance#8]
Dommage il manque des paramètre de paramétrage comme par exemple : 
- TITLE
- LOGO
- OrderText

**Comment by wysow** [comment]
Bonjour, ce projet étant open source n'hésitez pas à proposer une pull request pour ajouter les paramètres qui vous semblent nécessaires.

**Comment by wysow** [comment]
Je ferme cette issue, n'hésitez pas à produire une PR pour répondre à votre besoin.
